//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWS_FLY_TA.ServiceReference_NYP_Registration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_NYP_Registration.IWs_Registrationsvc")]
    public interface IWs_Registrationsvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Registrationsvc/getStudentNecessaryInfo", ReplyAction="http://tempuri.org/IWs_Registrationsvc/getStudentNecessaryInfoResponse")]
        System.Data.DataSet getStudentNecessaryInfo(int osepID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Registrationsvc/getStudentNecessaryInfo", ReplyAction="http://tempuri.org/IWs_Registrationsvc/getStudentNecessaryInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStudentNecessaryInfoAsync(int osepID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWs_RegistrationsvcChannel : AWS_FLY_TA.ServiceReference_NYP_Registration.IWs_Registrationsvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_RegistrationsvcClient : System.ServiceModel.ClientBase<AWS_FLY_TA.ServiceReference_NYP_Registration.IWs_Registrationsvc>, AWS_FLY_TA.ServiceReference_NYP_Registration.IWs_Registrationsvc {
        
        public Ws_RegistrationsvcClient() {
        }
        
        public Ws_RegistrationsvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_RegistrationsvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_RegistrationsvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_RegistrationsvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getStudentNecessaryInfo(int osepID) {
            return base.Channel.getStudentNecessaryInfo(osepID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStudentNecessaryInfoAsync(int osepID) {
            return base.Channel.getStudentNecessaryInfoAsync(osepID);
        }
    }
}
